name: amped
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - cudatoolkit=11.0
  - pytorch
  - pip
  - pip:
    - ray[rllib]==1.0.1.post1
    - gym-super-mario-bros==7.3.2
    - slack_sdk
    - -e .